services:
  database:
    container_name: litstore_db
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: litstore_redis
    image: "redis:alpine"
  api:
    container_name: litstore_api
    image: wiktoz/litstore-api:latest
    build: .
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:  
  pgdata: {}