services:
  database:
    container_name: database
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: api
    image: wiktoz/litstore-api:latest
    build: .
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:  
  pgdata: {}